[이예솔] Mission 5: 회원가입 비밀번호 암호화 적용
wecode-bootcamp-korea/30-westagram-backend-2-team pull request #17
Opened 2022-02-21 06:52 UTC by wingna1

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- bcrypt 사용해 회원가입 시 비밀번호 암호화 적용 후 DB 저장
- 사용 용이를 위해 email과 password 변수 생성
		 
## 수정 사항들 자세한 내용
- 입력받은 input_password를 인코딩해 hashed_password에 저장
- checkpw로 원 비교확인 후 문제 없을 시 hashed_password를 DB에 create

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-02-21 06:59 UTC, pasitoapasito commented on students/yesol/westagram/users/views.py
> +                    phone_number = data["phone_number"]
혹시 hashed_password를 decode하지 않고도 db에 저장할 수 있나요?? 궁금합니다 ㅎ _ㅎ

2022-02-21 07:30 UTC, kkookkss commented on students/yesol/westagram/users/views.py
> +            hashed_password = b.hashpw(input_password.encode("utf-8"), b.gensalt())
decode를 통해  str화 되지 않아도 데이터베이스엔 해싱된 password가 들어가는 것이니 저장되는 데이터형식의 차이만 있고 보안상으론 차이가 없는지 궁금합니다.

2022-02-21 07:36 UTC, wingna1 commented
찾아봤을 때 db에 넣을 때 반드시 디코딩해서 문자열로 넣어야 한다고 했는데, 디코딩 없이 바이트로도 삽입이 됩니다. 삽입된 형태가 다른데요, 이대로 사용해도 꺼낼 때 따로 처리를 해 준다면 상관이 없는 것인지, 아니면 그래도 문자열로 수정해야 하는지 궁금합니다.

`$2b$12$us1ju/tkVr0FgN3KKiNHXe8rLp341ClsMcc00pzbSyGJMqAL.Q7xy` # 한 것
`b'$2b$12$NraJXygm1fv3jQ9785koxuIKtGnoGrSg85sI3tadT.QZEHPHEi3qq'` # 안 한 것

2022-02-21 07:49 UTC, wingna1 commented on students/yesol/westagram/users/views.py
> +                    phone_number = data["phone_number"]
네 db에 저장되는데 형태가 조금 달라져서요! 해싱은 작동하되 타입만 다른 것 같아 이 방식이 문제가 없다면 그냥 써도 되지 않을까 싶어서 그대로 사용해 보았습니다

2022-02-21 07:51 UTC, wingna1 commented on students/yesol/westagram/users/views.py
> +            hashed_password = b.hashpw(input_password.encode("utf-8"), b.gensalt())
아래에 작성한 코멘트처럼 db에 저장되는 값의 형태가 조금 다르긴 한데 다른 문제는 없는 것 같아서 push했어요 !

2022-02-21 08:20 UTC, wingna1 commented
해시된 비밀번호를 decode하여 str로 변환 후 삽입하도록 수정하였습니다.
checkpw에서는 encode하여 사용합니다.

2022-02-21 08:48 UTC, Kang-kyunghun requested changes

2022-02-21 08:48 UTC, Kang-kyunghun commented on students/yesol/westagram/users/views.py
> +            input_password = data["password"]
```suggestion
            password = data["password"]
```
password로도 충분할 것 같습니다.

2022-02-21 08:48 UTC, Kang-kyunghun commented on students/yesol/westagram/users/views.py
> +import json, re, bcrypt as b
as b를 사용하면 오히려 가독성이 안 좋아진 것 같습니다. 빼주시면 좋을 것 같아요.

2022-02-21 08:48 UTC, Kang-kyunghun commented on students/yesol/westagram/users/views.py
> +            if b.checkpw(input_password.encode("utf-8"), hashed_password.encode("utf-8")):
password를 다시 확인하는 이유가 무엇일까요??

2022-02-21 11:39 UTC, wingna1 commented on students/yesol/westagram/users/views.py
> +            if b.checkpw(input_password.encode("utf-8"), hashed_password.encode("utf-8")):
제가 bcrypt관련 참고했던 글에서 해싱이 잘 되었는지 확인하면서 checkpw()를 사용해서 저도 잘 되었나 확인 후에 삽입하게 작성했는데... 잘 들어가는 것도 확인했고 else로 틀린 경우를 상정해 보다가 들어갈 게 없는 것 같아 뺐었습니다. checkpw()와 if문도 삭제하도록 하겠습니다!

2022-02-21 11:42 UTC, wingna1 commented
- 불필요한 checkpw()와 if문 삭제
- 변수명, import 패키지 닉네임 변경

2022-02-22 01:11 UTC, Kang-kyunghun commented
LGTM~~

2022-02-22 01:11 UTC, merged