[윤명국] Mission 6: 로그인 JWT 발급
wecode-bootcamp-korea/30-westagram-backend-2-team pull request #21
Opened 2022-02-21 16:30 UTC by kkookkss

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 비밀번호 확인 로직 추가 및 JWT 발급 기능 추가
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 데이터베이스에 암호화되어 저장된 비밀번호와 로그인시 입력된 비밀번호가 일치하는지 검증하는 로직 추가
(bcrypt의 checkpw method 이용)
- email 및 비밀번호가 검증되면 user_id를 포함하여 해쉬알고리즘(HS256)이 적용된 token이 발급되도록 설정

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-02-21 23:30 UTC, pasitoapasito commented on students/myungkookyoon/users/views.py
> +                    access_token = jwt.encode({'id': user.id}, SECRET_KEY, algorithm='HS256')
제 생각에는 algorithm 값을 my.settings.py에 넣어서 views.py로 import 받는 방법이 토큰 보안을 더욱 강화하는 방법인 것 같은데 이 부분에 대해 명국님의 의견이 궁금합니다~~!!

2022-02-22 00:23 UTC, wingna1 commented on students/myungkookyoon/users/views.py
> +                    access_token = jwt.encode({'id': user.id}, SECRET_KEY, algorithm='HS256')
저도 이 부분 동의합니다! secret_key처럼 이용하는 게 더 안전할 것 같아요.

2022-02-22 00:23 UTC, wingna1 commented on students/myungkookyoon/users/views.py
> +            if User.objects.filter(email=email).exists():
이중 if문으로 이메일 확인 후 객체에 담아 판별하는 방법 가독성도 좋고 깔끔한 것 같아요!

2022-02-22 01:19 UTC, Kang-kyunghun requested changes

2022-02-22 01:19 UTC, Kang-kyunghun commented on students/myungkookyoon/users/views.py
> +                    access_token = jwt.encode({'id': user.id}, SECRET_KEY, algorithm='HS256')
동기분들의 리뷰대로 algrithm도 secret_key처럼 사용할 수 있게 수정해 주세요.

2022-02-22 01:19 UTC, Kang-kyunghun commented on students/myungkookyoon/users/views.py
> +            if User.objects.filter(email=email).exists():
if 조건을 존재하면으로 시작 했는데, 만약 존재하지 않으면으로 시작하게 되면 코드가 어떻게 바뀔지 한 번 수정해 보시면 좋을 것 같습니다.

2022-02-22 01:40 UTC, kkookkss commented on students/myungkookyoon/users/views.py
> +                    access_token = jwt.encode({'id': user.id}, SECRET_KEY, algorithm='HS256')
말씀해주신 부분 생각해보니 my_settings.py에 넣는게 토큰 보안을 강화하는데 좋은 방법인것 같습니다.
감사합니다!

2022-02-22 02:19 UTC, kkookkss commented on students/myungkookyoon/users/views.py
> +                    access_token = jwt.encode({'id': user.id}, SECRET_KEY, algorithm='HS256')
네 수정하겠습니다~!

2022-02-22 02:29 UTC, kkookkss commented on students/myungkookyoon/users/views.py
> +            if User.objects.filter(email=email).exists():
네 if not로 시작하여 수정해보도록 하겠습니다.

2022-02-22 02:30 UTC, kkookkss commented on students/myungkookyoon/users/views.py
> +            if User.objects.filter(email=email).exists():
리뷰 감사합니다!

2022-02-22 06:05 UTC, Kang-kyunghun requested changes

2022-02-22 06:05 UTC, Kang-kyunghun commented on students/myungkookyoon/users/views.py
> +                return JsonResponse({'MESSAGE':'INVALID_USER'}, status=401)
```suggestion
                return JsonResponse({'message':'INVALID_USER'}, status=401)
```
보통 키값은 소문자로 많이 사용합니다.

2022-02-22 06:08 UTC, kkookkss commented on students/myungkookyoon/users/views.py
> +                return JsonResponse({'MESSAGE':'INVALID_USER'}, status=401)
네 확인했습니다 수정하겠습니다!

2022-02-22 06:24 UTC, Kang-kyunghun commented
LGTM~~!

2022-02-22 06:24 UTC, merged